HTTP_POST = "POST"
HTTP_DELETE = "DELETE"
SECRET_KEY = "discogs"
ISSUER = "https://www.discogs.com/"
MESSAGE_TOKEN_BLACKLISTED = "Token is now blacklisted"
MESSAGE_TOKEN_UNBLACKLISTED = "Token has been removed from blacklist"
MESSAGE_TOKEN_NO_LONGER_BLACKLISTED = "Token no longer blacklisted",
ERROR_NO_TOKEN_PROVIDED = "No token provided",
ERROR_BLACKLISTED_DUPLICATE = "Token already blacklisted"
ERROR_CANNOT_ADD_INVALID_ISSUER = "Token is not valid. Incorrect issuer",
ERROR_CANNOT_DELETE_INVALID_ISSUER = "Cannot delete token. Incorrect issuer",
ERROR_TOKEN_EXPIRED = "Token is no longer valid. Please login"